#!/bin/bash
set -e

export FLASK_APP=inf349
export FLASK_DEBUG=True
export DB_HOST=localhost
export DB_USER=user
export DB_PASSWORD=pass
export DB_PORT=5432
export DB_NAME=api8inf349
export REDIS_URL=redis://localhost

flask run